language: android

env:
  - GRADLE_OPTS="-Xmx2048m -XX:MaxPermSize=256m"

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - tools
    - android-25
    - build-tools-25.0.2
    - add-on
    - extra
